name: test setup-sigstore-env
on:
  workflow_dispatch:
  push:
    paths:
      - 'actions/setup-sigstore-env/**'
  pull_request:
    paths:
      - 'actions/setup-sigstore-env/**'
jobs:
  test:
    name: Test Sigstore setup
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Docker on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        id: setup-docker
        uses: douglascamata/setup-docker-macos-action@5643cfd7e434881308f89f2f3ae8852da11df909 # v1.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        # with:
        #   driver: docker
      - id: setup-sigstore-env
        uses: ./actions/setup-sigstore-env
      - uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0
        with:
          cosign-release: main
      - name: Create artifact to sign
        run: head -c 128 < /dev/urandom > artifact
      - name: Run cosign sign-blob
        env:
          SIGSTORE_CT_LOG_PUBLIC_KEY_FILE: ${{ steps.setup-sigstore-env.outputs.ct-log-key }}
          STEPS_SETUP_SIGSTORE_ENV_OUTPUTS_OIDC_URL: ${{ steps.setup-sigstore-env.outputs.oidc-url }}
          STEPS_SETUP_SIGSTORE_ENV_OUTPUTS_OIDC_TOKEN: ${{ steps.setup-sigstore-env.outputs.oidc-token }}
        run: |
          echo token:
          curl -f ${STEPS_SETUP_SIGSTORE_ENV_OUTPUTS_OIDC_URL}/token
          cosign sign-blob \
            -y \
            --bundle=bundle.json \
            --new-bundle-format=true \
            --rekor-url http://localhost:3000 \
            --fulcio-url http://localhost:5555 \
            --identity-token ${STEPS_SETUP_SIGSTORE_ENV_OUTPUTS_OIDC_TOKEN} \
            artifact
      - name: Run cosign verify-blob with trusted root
        run: |
          cosign verify-blob \
            --trusted-root ${STEPS_SETUP_SIGSTORE_ENV_OUTPUTS_TRUSTED_ROOT} \
            --bundle bundle.json \
            --new-bundle-format=true \
            --certificate-identity foo@bar.com \
            --certificate-oidc-issuer ${STEPS_SETUP_SIGSTORE_ENV_OUTPUTS_ISSUER_URL} \
            artifact
        env:
          STEPS_SETUP_SIGSTORE_ENV_OUTPUTS_TRUSTED_ROOT: ${{ steps.setup-sigstore-env.outputs.trusted-root }}
          STEPS_SETUP_SIGSTORE_ENV_OUTPUTS_ISSUER_URL: ${{ steps.setup-sigstore-env.outputs.issuer-url }}
